# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

disqus_shortname: https-razorthinksoftware-github-io

# Setup
title:            DeepThink
tagline:          "Razorthink's inhouse RSS Feed!"
description:      "Razorthink's inhouse RSS Feed! What's the happening trend in the domain of Artificial Intelligence?"

url:              https://github.com/razorthinksoftware/deepthink
baseurl:          /deepthink/

author:
  name:           'Prathyush SP'
  url:            https://github.com/kingspp

paginate:         10

# Custom vars
version:          1.3

github:
  url:            https://github.com/razorthinksoftware/deepthink

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]

plugins:
  - jekyll-paginate
  - redcarpet
  - pygments.rb

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]